### ISSUE TITLE
pip3 installation fails on my debian/testing system

### ISSUE THREAD

**Issue by ghost** [amezin/amdgpu-pptable-editor-qt#1]
Hello amezin,

i tried to install the current version of this great tool, following your instructions, but get the following trouble:

[pip.log](https://github.com/amezin/amdgpu-pptable-editor-qt/files/4404352/pip.log)

Do you have an idea what i'am doing wrong? Maybe there is an directory mismatch in a script?

Thank you very much.

**Comment by amezin** [comment]
Added a workaround to "Installation" section in README: https://github.com/amezin/amdgpu-pptable-editor-qt#installation

**Comment by ghost** [comment]
... this workaround works great for me ...
Thank you.
